Document: moflow900
Title: Debian moflow900 Manual
Author: <insert document author here>
Abstract: This manual describes what moflow900 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/moflow900/moflow900.sgml.gz

Format: postscript
Files: /usr/share/doc/moflow900/moflow900.ps.gz

Format: text
Files: /usr/share/doc/moflow900/moflow900.text.gz

Format: HTML
Index: /usr/share/doc/moflow900/html/index.html
Files: /usr/share/doc/moflow900/html/*.html

  
